### PR TITLE
Updated offsets

### PR DESCRIPTION
**Pull request by xCENTx**
Update SDK.hpp
- Gobjects
- AppendString
- ProcessEvent

Update config.h
- APalPlayerCharacter::Tick

### CODE REVIEW

**Comment by qh1327966381** [comment]
> 更新 SDK.hpp
> 
> * G对象
> * AppendString
> * ProcessEvent
> 
> 更新 config.h
> 
> * APalPlayerCharacter：：勾选

应该要怎么修改

**Comment by qh1327966381** [comment]
> 更新 SDK.hpp
> 
> * G对象
> * AppendString
> * ProcessEvent
> 
> 更新 config.h
> 
> * APalPlayerCharacter：：勾选


明白了，真挚的感谢你

**Comment by xCENTx** [comment]
> 应该要怎么修改

https://github.com/swordbluesword/PalWorld-NetCrack/pull/37/files

**Comment by AngeQLF** [comment]
Hi, do you know why when i go in "Database" my game is crashing with the error "Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000008" ?

**Comment by geocine** [comment]
How do you find this offsets care to share @xCENTx

**Pull request merged**
