### PR TITLE
add all effigies and ability to multiply item slots.

### PR DESCRIPTION
**Pull request by BennettStaley**
adds two new buttons, all effigies and 2x the first item in your inventory.

### CODE REVIEW

**Review by xCENTx — CHANGES_REQUESTED** [review]
Great additions! Would it be too much to ask to have the functions declared in [features header](https://github.com/swordbluesword/PalWorld-NetCrack/blob/master/feature.h) and defined in [features source](https://github.com/swordbluesword/PalWorld-NetCrack/blob/master/feature.cpp)

Here's an example implementation, then another function could be created which calls this one directly with a count that would be "x2" for instance. It also cleans up the area where widgets are implemented make it much easier to work with the UI , you'd only see a call to a function for the feature in question as opposed to multiple lines of code. It allows for the feature to be accessed elsewhere as well
```cpp
void AddToInventoryContainer(__int32 mCount, __int32 mIndex = 0)
{
	SDK::APalPlayerCharacter* p_appc = Config.GetPalPlayerCharacter();
	if (!p_appc != NULL)
		return;
	
	SDK::APalPlayerController* p_apc = static_cast<APalPlayerController*>(p_appc->Controller);
	if (!p_apc)
		return;

	SDK::APalPlayerState* p_apps = static_cast<SDK::APalPlayerState * >(p_apc->PlayerState);
	if (!p_apps)
		return;

	SDK::UPalPlayerInventoryData* InventoryData = p_apps->GetInventoryData();
	if (!InventoryData)
		return;
	
	SDK::UPalItemContainerMultiHelper* InventoryMultiHelper = InventoryData->InventoryMultiHelper;
	if (!InventoryMultiHelper)
		return;

	SDK::TArray<class SDK::UPalItemContainer*> Containers = InventoryMultiHelper->Containers;
	if (Containers.Count() <= 0)
		return;
			
	SDK::UPalItemSlot* pSelectedSlot = Containers[0]->Get(mIndex);

	if (!pSelectedSlot != NULL)
		return;

	SDK::FPalItemId FirstItemId = pSelectedSlot->GetItemId();
	int32 StackCount = pSelectedSlot->GetStackCount();
	__int32 mNewCount = StackCount += mCount;
	InventoryData->RequestAddItem(FirstItemId.StaticId, mNewCount, true);
}
```

**Comment by BennettStaley** [comment]
Nice. I'll implement this after work. Also want to get a barebones ESP working.

**Comment by xCENTx** [comment]
> Nice. I'll implement this after work. Also want to get a barebones ESP working.

I merged your initial changes into a pr i was in the middle of , it still gives you credit for your contributions, figured it would make things easier. I will included the snipped above but leave it up to you if you want to make adjustments to the way things are called via the button press at this current time

**Comment by BennettStaley** [comment]
> I merged your initial changes into a pr i was in the middle of , it still gives you credit for your contributions, figured it would make things easier. 

I'll make those adjustments and add another commit, then you can merge them into your PR and we can track work there. Much appreciated.

re-learning this C++ and Unreal stuff, your comments are extremely helpful :)

**Comment by BennettStaley** [comment]
@xCENTx Changes made. great suggestions. Correct me if im wrong but the =0 in the header file should catch if the index isn't included right?

**Pull request merged**
