### PR TITLE
Features and Adjustments

### PR DESCRIPTION
**Pull request by xCENTx**
SDK
- Changed TArray function name "Num" to "Count" for clarity

CONFIG
- included additional helper functions

FEATURE
- General cleanup
- Include features as functions

NOTES:
- new feature functions have not been implemented

### CODE REVIEW

**Comment by RayshenOmega** [comment]
So i just tried to compile that and it failed with these error's

**"FSoftObjectPath" is undefined	NetCrack-PalWorld	D:\case\repos\SDK\Basic.hpp	458**		
```
public:
	FString GetSubPathString();
	std::string GetSubPathStringStr();

	template<class SoftObjectPath = FSoftObjectPath>
	SoftObjectPath& GetObjectPath();
};
```
config.cpp
**'GetCharacterImpManager': function must return a value	NetCrack-PalWorld	D:\case\repos\config.cpp	53**		
```
SDK::UPalCharacterImportanceManager* GetCharacterImpManager()
{
    SDK::UWorld* pWorld = config::gWorld;
    if (!pWorld)
        return;

    SDK::UGameInstance* pGameInstance = pWorld->OwningGameInstance; 
    if (!pGameInstance) 
        return nullptr;

    return static_cast<SDK::UPalGameInstance*>(pGameInstance)->CharacterImportanceManager;
}
```

feature.ccp
**'SetCraftingSpeed': redefinition of default argument: parameter 1	NetCrack-PalWorld	D:\case\repos\feature.cpp	78**		
```
void SetCraftingSpeed(float mNewSpeed, bool bRestoreDefault = false)
{
	APalPlayerCharacter* pPalCharacter = Config.GetPalPlayerCharacter();
	if (!pPalCharacter)
		return;

	UPalCharacterParameterComponent* pParams = pPalCharacter->CharacterParameterComponent;
	if (!pParams)
		return;

	UPalIndividualCharacterParameter* ivParams = pParams->IndividualParameter;
	if (!ivParams)
		return;

	FPalIndividualCharacterSaveParameter sParams = ivParams->SaveParameter;
	TArray<FFloatContainer_FloatPair> mCraftSpeedArray = sParams.CraftSpeedRates.Values;

	if (mCraftSpeedArray.Count() > 0)
		mCraftSpeedArray[0].Value = bRestoreDefault ? 1.0f : mNewSpeed;
}
```

**Comment by xCENTx** [comment]
> So i just tried to compile that and it failed with these error's
> 
> **"FSoftObjectPath" is undefined NetCrack-PalWorld D:\case\repos\SDK\Basic.hpp 458**
> **'GetCharacterImpManager': function must return a value NetCrack-PalWorld D:\case\repos\config.cpp 53**
> **'SetCraftingSpeed': redefinition of default argument: parameter 1 NetCrack-PalWorld D:\case\repos\feature.cpp 78**

these errors have been addressed in the latest push

**Comment by xCENTx** [comment]
merged [6b548a4](https://github.com/swordbluesword/PalWorld-NetCrack/pull/24/commits/6b548a4756cdbea80ca7eca40585e4614a84086b)

**Comment by BennettStaley** [comment]
Oooh these are slick.

**Comment by BennettStaley** [comment]
I'd love to see the esp filter out based on a char input box. So you can effectively "search" for the pal you wanted.

Also feel free to pull in my latest commit. LMK if you have any more reqs.

**Comment by itzkaydo** [comment]
`Build started: Project: SoTMaulder-PalWorld, Configuration: Release x64 ------
1>Menu.obj : error LNK2001: unresolved external symbol "void __cdecl ESP_DEBUG(double,class SDK::UClass *)" (?ESP_DEBUG@@YAXNPEAVUClass@SDK@@@Z)
1>  Hint on symbols that are defined and could potentially match:
1>    "void __cdecl ESP_DEBUG(float,struct ImVec4,class SDK::UClass *)" (?ESP_DEBUG@@YAXMUImVec4@@PEAVUClass@SDK@@@Z)
1>C:\Users\itzkaydo\Desktop\Palword\SoTMaulder-PalWorld\x64\Release\SoTMaulder-PalWorld.dll : fatal error LNK1120: 1 unresolved externals`

**Comment by killercc** [comment]
any good idea to fix low fps ?
losed 50~60 fps , even without drawing

**Comment by yeetmans** [comment]
> `Build started: Project: SoTMaulder-PalWorld, Configuration: Release x64 ------ 1>Menu.obj : error LNK2001: unresolved external symbol "void __cdecl ESP_DEBUG(double,class SDK::UClass *)" (?ESP_DEBUG@@YAXNPEAVUClass@SDK@@@Z) 1> Hint on symbols that are defined and could potentially match: 1> "void __cdecl ESP_DEBUG(float,struct ImVec4,class SDK::UClass *)" (?ESP_DEBUG@@YAXMUImVec4@@PEAVUClass@SDK@@@Z) 1>C:\Users\itzkaydo\Desktop\Palword\SoTMaulder-PalWorld\x64\Release\SoTMaulder-PalWorld.dll : fatal error LNK1120: 1 unresolved externals`

@swordbluesword just merged @geocine 's fix for it, there was a different signature defined in feature.h and menu.cpp, causing that error.

**Pull request merged**
